<h1>현장실습 18일차</h1>

CAD 명령어 '원의 접선 그리기' 완성  

전날 다이얼로그를 완성하였기 때문에 오전에는 다른 팀원들이 기능을 완성할 동안 <br>
여러 프로그래밍 언어를 찾아보고 공부했다. <br><br>

점심이 다 될 때쯤 과제 중 하나의 기능을 맡게 되었다. <br>
완성해야할 기능은 각각의 객체를 블록화 시키는 기능이다. <br><br>

퇴근 전까지 무조건 완성해야하기 때문에 급하게 기능 제작을 시작했다. <br>
우선 접선이 담겨있는 OdDbEntityPtrArray 엔티티 배열에서 접선을 하나씩 가져와서 <br>
OdDbBlockTableRecordPtr 테이블레코드에 추가시켰다. <br><br>

원 또한 OdDbObjectIdArray 오브젝트아이디 배열에서 하나씩 가져와서 <br>
OdDbCirclePtr 원 포인터로 캐스팅 해준 뒤 테이블레코드에 추가시켜줬다. <br><br>

하지만 추가시키는 부분에서 예외가 발생하였고, 몇 시간동안 해결하지 못했다. <br>
팀원에게 도움을 요청하였고 다행히 마감 시간 내 완성할 수 있었다. <br><br>

발생한 문제점은 메인 테이블레코드에 추가되어 있는 객체를 또 다른 레코드에 추가하려고 하니 <br>
충돌이 생긴 것이다. <br>
그래서 clone()을 사용하여 객체를 복사한 뒤, 복사된 객체를 새로 생성한 테이블 레코드에 추가시켜줬다. <br><br>

테스트해 본 결과, 정상적으로 각각의 객체들이 블록화 되어 제대로 작동이 되었다. <br>

<hr>
<h3>실습</h3>
CAD 개발 - '원의 접선 그리기' 명령어 제작 완료
개인 발표 준비
